### PR TITLE
Bf tidier mr isample distances

### PR DESCRIPTION
**Pull request by emtpgeek**
DON'T PULL THIS WITHOUT RESOLVING THE USES OF VERTEX.nsize AS DESCRIBED BELOW!

Gets identical results with recon-all bert

Adds a much better consistency checker, and fixes several bugs it discovered - fortunately none of them changing the results of recon-all

VERTEX.nsize has been split into VERTEX.nsizeMax and VERTEX.nsizeCur, clarifying which of the two is intended.  As in the old code  MRIS.max_nsize and MRIS.nsize continue to exist.  nsizeMax tells which of the .vnum, .v2num, .v3num are valid.  .nsizeCur indicates which of these was used to compute .vtotal.  The .v[*] and .dist[*] and .dist_orig[*] hold at least .nsizeMax's indicated .v#num values, and also hold at least .vtotal values.  

I have fixed all the uses in the code I can compile without getting VTK and KWWidgets to compile - I have been trying to get those built as well, but the packages/... for those aren't successfully built on my system.

If some of the remaining code is reading VERTEX.nsize, it will be context specific whether they intend .nsizeCur or .nsizeMax.  That is why I changed the name.

The remaining code should NOT be writing either of these fields, and soon I will be disabling their ability to do so.  There are too many other things that need to be kept consistent, so only a handful of functions in mris*c code should be changing these.

### CODE REVIEW

**Comment by ahoopes** [comment]
Accidentally merged this - just committed a revert. I'll re-merge the changes once the nsize uses are resolved.

**Comment by ahoopes** [comment]
Okay, everything compiles successfully. It seems like you aready covered all the uses of vertex.nsize

**Comment by emtpgeek** [comment]
I guess I should have sent you email as well as putting it in the comment section

On Sep 30, 2018 12:12 PM, Andrew Hoopes <notifications@github.com> wrote:

Accidentally merged this - just committed a revert

**Comment by emtpgeek** [comment]
Phew...

On Sep 30, 2018 12:57 PM, Andrew Hoopes <notifications@github.com> wrote:

Okay, everything compiles successfully. It seems like you aready covered all the uses of vertex.nsize

**Comment by emtpgeek** [comment]
My next pull request has the same risk. Rather than fixing them yourself you can just send me the compilation error look if you like.

On Sep 30, 2018 1:02 PM, Bevin Brett <bevin_brett@hotmail.com> wrote:
Phew...

On Sep 30, 2018 12:57 PM, Andrew Hoopes <notifications@github.com> wrote:

Okay, everything compiles successfully. It seems like you aready covered all the uses of vertex.nsize

**Pull request merged**
