### PR TITLE
An alternative implementation of MRISaverageGradients 

### PR DESCRIPTION
**Pull request by emtpgeek**
This implementation is approx 8x faster resulting in an overall speedup of mris_register of about 2x.

It does this by moving the ripflag tests out of the loop and getting just the relevant data into a temporary secondary data structure that is much denser and hence makes much better use of cache and memory traffic.

Since this function takes up almost all of mris_register's time, it is worth this level of optimization, since this brings my timing run down from 0.25 hours to 0.13 hours

### CODE REVIEW

**Review by chrisadamsonmcri — COMMENTED** [review]
Great work.
Small change. A 1-left bit shift could replace the multiplication on line 10942.

**Comment by emtpgeek** [comment]
You are right, but I expect that an optimizing compiler will replace
    limit *= 2
with either
    limit += limit
or
   limit <<= 1
which ever, depending on the machine, faster.   

Thank you for reading through the change and noticing this.

**Comment by emtpgeek** [comment]
Now I have to figure out why the checks failed...

**Comment by emtpgeek** [comment]
Looks like a build system problem

"GPG error: http://repo.mongodb.org/apt/ubuntu trusty/mongodb-org/3.2 Release: The following signatures were invalid: KEYEXPIRED 1507497109"

**Comment by ahoopes** [comment]
Fixed now. I'll accept the pull after tests of the current repo finish up

**Comment by chrisadamsonmcri** [comment]
Good point. After reading on this the compiler should optimise with a bit-shift for a times 2 multiplication.

**Pull request merged**
